server:
  port: 8085

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Base URLs for sync Feign calls to other services
services:
  crop-service:
    url: http://localhost:8084
  dealer-service:
    url: http://localhost:8083