server:
  port: 8083

spring:
  application:
    name: dealer-service

  datasource:
    url: jdbc:mysql://localhost:3306/dealer_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest